# Generated by Django 4.2.1 on 2023-06-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0002_alter_majors_governorate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majors',
            name='governorate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Governorate_set', to='Admission.governorate'),
        ),
    ]
