# Generated by Django 4.2.1 on 2023-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0004_alter_majors_governorate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majors',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(True, 'ذكر'), (False, 'أنثى')]),
        ),
    ]
