# Generated by Django 4.2.3 on 2023-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_admission_certificate_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_num',
            field=models.IntegerField(null=True),
        ),
    ]
