# Generated by Django 4.2.3 on 2023-08-16 12:36

import Student.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0006_alter_majors_gender'),
        ('Student', '0004_alter_admission_admission_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_type', to='Admission.admissiontype'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_admission', to='Student.student'),
        ),
        migrations.AlterField(
            model_name='admissiondesire',
            name='admission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_desire_set', to='Student.admission'),
        ),
        migrations.AlterField(
            model_name='admissionrequirements',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=Student.models.upload_profile_image_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
