# Generated by Django 4.2.3 on 2023-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_admission_admission_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequirements',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
